["    @Test\n    public void test1() throws Throwable {\n        if (debug)\n            System.out.format(\"%n%s%n\", \"RegressionTest0.test1\");\n        java.io.File file1 = null;\n        // The following exception was thrown during execution in test generation\n        try {\n            org.apache.pulsar.functions.utils.FunctionCommon.downloadFromHttpUrl(\"\", file1);\n            org.junit.Assert.fail(\"Expected exception of type java.net.MalformedURLException; message: no protocol: \");\n        } catch (java.net.MalformedURLException e) {\n            // Expected exception.\n        }\n    }\n", "    @Test\n    public void test2() throws Throwable {\n        if (debug)\n            System.out.format(\"%n%s%n\", \"RegressionTest0.test2\");\n        java.io.File file1 = null;\n        // The following exception was thrown during execution in test generation\n        try {\n            org.apache.pulsar.functions.utils.FunctionCommon.downloadFromHttpUrl(\"hi!\", file1);\n            org.junit.Assert.fail(\"Expected exception of type java.net.MalformedURLException; message: no protocol: hi!\");\n        } catch (java.net.MalformedURLException e) {\n            // Expected exception.\n        }\n    }\n"]